export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahrain",
  "Bangladesh",
  "Belarus",
  "Belgium",
  "Bolivia",
  "Brazil",
  "Bulgaria",
  "Cambodia",
  "Canada",
  "Chile",
  "China",
  "Colombia",
  "Croatia",
  "Czech Republic",
  "Denmark",
  "Ecuador",
  "Egypt",
  "Estonia",
  "Finland",
  "France",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Latvia",
  "Lebanon",
  "Lithuania",
  "Luxembourg",
  "Malaysia",
  "Mexico",
  "Morocco",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "Norway",
  "Pakistan",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Saudi Arabia",
  "Singapore",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sweden",
  "Switzerland",
  "Thailand",
  "Turkey",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Venezuela",
  "Vietnam",
  "Other",
];

export const languages = [
  "Afrikaans",
  "Albanian",
  "Arabic",
  "Armenian",
  "Bengali",
  "Bulgarian",
  "Catalan",
  "Chinese (Mandarin)",
  "Chinese (Cantonese)",
  "Croatian",
  "Czech",
  "Danish",
  "Dutch",
  "English",
  "Estonian",
  "Filipino",
  "Finnish",
  "French",
  "German",
  "Greek",
  "Hebrew",
  "Hindi",
  "Hungarian",
  "Icelandic",
  "Indonesian",
  "Italian",
  "Japanese",
  "Korean",
  "Latvian",
  "Lithuanian",
  "Malay",
  "Malayalam",
  "Norwegian",
  "Persian",
  "Polish",
  "Portuguese",
  "Punjabi",
  "Romanian",
  "Russian",
  "Serbian",
  "Slovak",
  "Slovenian",
  "Spanish",
  "Swahili",
  "Swedish",
  "Tamil",
  "Telugu",
  "Thai",
  "Turkish",
  "Ukrainian",
  "Urdu",
  "Vietnamese",
  "Other",
];

export const timezones = [
  "UTC-12:00 (Baker Island)",
  "UTC-11:00 (American Samoa)",
  "UTC-10:00 (Hawaii)",
  "UTC-09:00 (Alaska)",
  "UTC-08:00 (Pacific Time)",
  "UTC-07:00 (Mountain Time)",
  "UTC-06:00 (Central Time)",
  "UTC-05:00 (Eastern Time)",
  "UTC-04:00 (Atlantic Time)",
  "UTC-03:00 (Argentina, Brazil)",
  "UTC-02:00 (South Georgia)",
  "UTC-01:00 (Azores)",
  "UTC+00:00 (GMT, London)",
  "UTC+01:00 (Central Europe)",
  "UTC+02:00 (Eastern Europe)",
  "UTC+03:00 (Moscow, East Africa)",
  "UTC+04:00 (Gulf, Caucasus)",
  "UTC+05:00 (Pakistan, Kazakhstan)",
  "UTC+05:30 (India, Sri Lanka)",
  "UTC+06:00 (Bangladesh, Central Asia)",
  "UTC+07:00 (Thailand, Vietnam)",
  "UTC+08:00 (China, Singapore)",
  "UTC+09:00 (Japan, Korea)",
  "UTC+10:00 (Australia East)",
  "UTC+11:00 (Solomon Islands)",
  "UTC+12:00 (New Zealand)",
];

export const educationLevels = [
  "High School Diploma",
  "Associate Degree",
  "Bachelor's Degree",
  "Master's Degree",
  "Doctoral Degree (PhD)",
  "Professional Degree (MD, JD, etc.)",
  "Certificate Program",
  "Diploma",
  "Other",
];

export const expertiseAreas = [
  // Technology & Programming
  "JavaScript",
  "Python",
  "Java",
  "C++",
  "React",
  "Node.js",
  "Angular",
  "Vue.js",
  "Machine Learning",
  "Data Science",
  "Web Development",
  "Mobile Development",
  "Cloud Computing",
  "Cybersecurity",
  "DevOps",
  "AI/Artificial Intelligence",
  "Blockchain",
  "Database Management",

  // Business & Finance
  "Digital Marketing",
  "Project Management",
  "Business Analysis",
  "Accounting",
  "Finance",
  "Entrepreneurship",
  "Leadership",
  "Sales",
  "Human Resources",
  "Operations Management",

  // Design & Creative
  "Graphic Design",
  "UI/UX Design",
  "Photography",
  "Video Editing",
  "Animation",
  "Web Design",
  "Illustration",
  "Branding",

  // Languages
  "English Teaching",
  "Spanish",
  "French",
  "German",
  "Chinese",
  "Japanese",
  "Arabic",
  "Language Translation",

  // Academic Subjects
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "History",
  "Literature",
  "Psychology",
  "Philosophy",
  "Economics",
  "Political Science",

  // Health & Wellness
  "Nutrition",
  "Fitness Training",
  "Yoga",
  "Mental Health",
  "Medical Education",
  "Public Health",

  // Arts & Music
  "Music Theory",
  "Piano",
  "Guitar",
  "Violin",
  "Singing",
  "Music Production",
  "Fine Arts",
  "Sculpture",

  // Other
  "Communication Skills",
  "Public Speaking",
  "Writing",
  "Research Methods",
  "Critical Thinking",
  "Problem Solving",
  "Other",
];

export const socialMediaPlatforms = [
  {
    name: "LinkedIn",
    icon: "mdi:linkedin",
    placeholder: "https://linkedin.com/in/yourprofile",
    color: "text-blue-600",
  },
  {
    name: "Twitter",
    icon: "mdi:twitter",
    placeholder: "https://twitter.com/yourusername",
    color: "text-blue-400",
  },
  {
    name: "Facebook",
    icon: "mdi:facebook",
    placeholder: "https://facebook.com/yourprofile",
    color: "text-blue-700",
  },
  {
    name: "Instagram",
    icon: "mdi:instagram",
    placeholder: "https://instagram.com/yourusername",
    color: "text-pink-600",
  },
  {
    name: "YouTube",
    icon: "mdi:youtube",
    placeholder: "https://youtube.com/c/yourchannel",
    color: "text-red-600",
  },
  {
    name: "GitHub",
    icon: "mdi:github",
    placeholder: "https://github.com/yourusername",
    color: "text-gray-800",
  },
  {
    name: "Personal Website",
    icon: "mdi:web",
    placeholder: "https://yourwebsite.com",
    color: "text-green-600",
  },
];

export const fileUploadConfig = {
  image: {
    maxSize: 5 * 1024 * 1024, // 5MB
    allowedTypes: ["image/jpeg", "image/png", "image/jpg", "image/webp"],
    allowedExtensions: [".jpg", ".jpeg", ".png", ".webp"],
  },
  certificate: {
    maxSize: 10 * 1024 * 1024, // 10MB
    allowedTypes: [
      "application/pdf",
      "image/jpeg",
      "image/png",
      "image/jpg",
      "application/msword",
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ],
    allowedExtensions: [".pdf", ".jpg", ".jpeg", ".png", ".doc", ".docx"],
  },
};

export const validationMessages = {
  required: (field: string) => `${field} is required`,
  email: "Please enter a valid email address",
  phone: "Please enter a valid phone number (10-15 digits)",
  url: "Please enter a valid URL",
  minLength: (field: string, min: number) =>
    `${field} must be at least ${min} characters`,
  maxLength: (field: string, max: number) =>
    `${field} must not exceed ${max} characters`,
  passwordMatch: "Passwords must match",
  passwordStrength:
    "Password must contain at least one letter and one special character",
  fileSize: (maxSize: number) =>
    `File size must be less than ${maxSize / (1024 * 1024)}MB`,
  fileType: (allowedTypes: string[]) =>
    `Only ${allowedTypes.join(", ")} files are allowed`,
};

export const formSteps = {
  ACCOUNT_INFO: 0,
  PERSONAL_DETAILS: 1,
  EDUCATIONAL_DETAILS: 2,
  PROFESSIONAL_DETAILS: 3,
  CONTACT_LOCATION: 4,
  SOCIAL_MEDIA: 5,
} as const;

export const stepTitles = [
  {
    title: "Create Your Account",
    subtitle: "Set up your login credentials",
    icon: "mdi:account-plus",
  },
  {
    title: "Tell Us About Yourself",
    subtitle: "Help students get to know you better",
    icon: "mdi:account-circle",
  },
  {
    title: "Your Educational Background",
    subtitle: "Showcase your qualifications and expertise",
    icon: "mdi:school",
  },
  {
    title: "Professional Experience",
    subtitle: "Share your work experience and achievements",
    icon: "mdi:briefcase",
  },
  {
    title: "Contact Information",
    subtitle: "How can we reach you?",
    icon: "mdi:map-marker",
  },
  {
    title: "Social Media Presence",
    subtitle: "Connect your social profiles (optional)",
    icon: "mdi:share-variant",
  },
];
